### PR TITLE
foo

### LINKED ISSUE #8: sample-issue
blah blah blah

### PR DESCRIPTION
**Pull request by laurentran**
In this PR:
-modify readme

Closes #8

### CODE REVIEW

**Review by shivachittamuru — COMMENTED** [review]
blah blah

**Review by shivachittamuru — CHANGES_REQUESTED** [review]
requesting changes

**Comment by laurentran** [comment]
committed change as requested

**Review by shivachittamuru — APPROVED** [review]

**Comment by shivachittamuru** [comment]
Approving changes.

**Pull request closed without merging**
